server.servlet.context-path=/CitySkate
spring.application.name=CitySkate
spring.datasource.url=jdbc:sqlite:cityskate.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springdoc=INFO